apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blog-prod-database
  namespace: cnpg-system
spec:
  instances: 2

  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi
    storageClass: nfs-client