#Frontend deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: blog-prod
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-astro
          image: docker-registry-local.taild2a7e.ts.net/astro-app
          imagePullPolicy: Always
          ports:
            - containerPort: 4321
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
          - configMapRef:
              name: astro-blog-env
          - secretRef:
              name: astro-blog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: blog-prod
spec:
  selector:
    app: frontend
  ports:
  - port: 4321
    targetPort: 4321

# Backend
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: blog-prod
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker-registry-local.taild2a7e.ts.net/gin-backend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
            - configMapRef:
                name: astro-blog-env
            - secretRef:
                name: astro-blog-secret
              
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: blog-prod
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080

# ENV POSTGRES_HOST=
# ENV POSTGRES_PORT=
# ENV POSTGRES_USER=
# ENV POSTGRES_PASSWORD=
# ENV POSTGRES_NAME=
# ENV POSTGRES_SSLMODE=