apiVersion: v1
kind: ConfigMap
metadata:
  name: astro-blog-env
  namespace: blog-prod
data:
  POSTGRES_HOST: blog-prod-database-r.cnpg-system.svc.cluster.local
  POSTGRES_PORT: '5432'
  POSTGRES_USER: bloguser
  POSTGRES_NAME: blogdigestdb
  POSTGRES_SSLMODE: disable
  BACKEND_PORT: '8080'
  BACKEND_HOST: gin-backend.blog-prod.svc.cluster.local
  MINIO_USER: minioadmin
  MINIO_PORT: '9000'
  MINIO_HOST: localhost
  MINIO_USE_SSL: "false"