apiVersion: v1
kind: Secret
metadata:
  name: astro-blog-secret
  namespace: blog-prod
type: Opaque
data:
  HMAC_API_KEY: YWY5NzI1MTFiM2FhZTI1NDMwNjE5YTMyNmFhMjhmMzY2MjZjZWU1ZWQ1YzY5NzA2NTE2YmJjZTRkMzIzYzJiOQ==
  POSTGRES_PASSWORD: cTIzdWdwODMydDA=
  MINIO_PASS: bWluaW9hZG1pbg==
