apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuitscan
  namespace: blog-prod
spec:
  selector:
    matchLabels:
      app: circuitscan
  template:
    metadata:
      labels:
        app: circuitscan
    spec:
      containers:
      - name: circuitscan-wsgi
        image: unbounder/circuitscan:latest
        resources:
          limits:
            memory: "8G"
            cpu: "2"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: circuitscan-svc
  namespace: blog-prod
spec:
  selector:
    app: circuitscan
  ports:
  - port: 8001
    targetPort: 8001
