server:
  persistentVolume:
    enabled: true
    storageClass: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: true

  persistence:
    storageClass: nfs-client
    size: 2Gi

  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534
    fsGroup: 65534
