apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: prometheus
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/prometheus/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: prometheus
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/prometheus/grafana
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
