apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-share
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/public_share/kubernetes/zipline 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: zipline
            operator: In
            values:
              - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-share-claim
  namespace: zipline
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 4000Gi
  storageClassName: standard
