apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cnpg-system
type: kubernetes.io/basic-auth
data:
  username: YmxvZ3VzZXI=  # base64 encoded "postgres"
  password: cGFzc3dvcmQ=  # base64 encoded "password"