apiVersion: v1
kind: Service
metadata:
  name: blog-prod-database-rw-lb
  namespace: cnpg-system
spec:
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: blog-prod-database-rw 